color/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main_app.urls", namespace="main_app")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/urls.py
from django.urls import path

from . import views

app_name = "main_app"

urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),
    path("modified/", views.ModifiedImgView.as_view(), name="modified"),
    path("img/<pk>", views.ImgPageView.as_view(), name="img"),
]

main_app/models.py
from django.db import models


# Create your models here.
class Photo(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to="orginal_photos/")
    modified_image = models.ImageField(upload_to="modified_photos/")
    uploaded_at = models.DateTimeField(auto_now_add=True)
    all_files = models.FileField(upload_to='zips/')

    def __str__(self):
        return self.title

main_app/forms.py
# forms.py
from django import forms
from .models import Photo


# Form for Photo model
class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ["image"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["image"].widget.attrs.update({"class": "form-control-file"})

main_app/views.py
from typing import Any
from django.shortcuts import render, redirect
from django.views.generic import View, TemplateView, DetailView
from django.conf import settings
from .forms import PhotoForm
from .util_2 import main
from .models import Photo

# Create your views here.


# View for Home page
class HomePageView(TemplateView):
    template_name = "index.html"


# Show to modified images
class ImgPageView(DetailView):
    model = Photo
    template_name = "modified.html"


# Modified images
class ModifiedImgView(View):

    def post(self, request):
        form = PhotoForm(request.POST, request.FILES)

        if form.is_valid():
            f = form.save(commit=False)
            f.title = f.image.name
            f.save()
            pk = f.id

            main(
                f".{f.image.url}",
                f"./media/modified_img_{pk}.png",
                int(request.POST.get("num_clusters"))
            )

            photo = Photo.objects.get(id=pk)
            photo.modified_image = f"modified_img_{pk}_with_colors.png"
            photo.all_files = f"modified_img_{pk}.zip"
            photo.save()
            return redirect("main_app:img", pk=pk)
        return redirect("main_app:home")

templates/index.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>LOGO</title>
    <style>
        html,
        body {
            height: 100%;
        }

        .full-page {
            height: 65vh;
            background-color: light;
        }
    </style>
</head>

<body>
    <!-- navbar start -->
    <nav class="navbar navbar-light bg-primary ">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">LOGO</a>
        </div>
    </nav>
    <!-- navbar end -->
    <!-- main start -->
    <div class="card text-center">
        <div class="card-header">

        </div>
        <div class="card-body mt-5 full-page justify-content-center align-items-center">
            <h4 class="card-title">Создать картинку по номерам</h4>
            <p class="card-text">Выберите нужное изображение, нажав кнопку.</p>
            <div class="container">
                <div class="row justify-content-md-center">
                    <div class="col-12 col-sm-12 col-md-6">
                        <form action="{% url 'main_app:modified' %}" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <input class="form-control " type="file" id="formFile" accept="image/*" name="image">
                            <div class="mb-3">
                                <label for="exampleNumber" class="form-label">Выберите нужное изображение</label>
                                <input type="number" name="num_clusters" class="form-control" id="exampleNumber" placeholder="0" min="5" value="5">
                              </div>
                            <button class="btn btn-primary mt-3" type="submit">Редактирование</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer text-muted">

        </div>
    </div>
    <!-- main end -->
    <!-- footer star -->
    <footer class="footer text-center bg-primary p-4 bg-base-300 text-base-content">
        <div>
            <p>Copyright © 2024 - All right reserved by LOGO</p>
        </div>
    </footer>
    <!-- footer end -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
        </script>


</body>

</html>

templates/modified.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>LOGO</title>
    <style>
        html,
        body {
            height: 100%;
        }

        .full-page {
            height: 70vh;
            background-color: light;
        }
    </style>
</head>

<body>
    <!-- navbar start -->
    <nav class="navbar navbar-light bg-primary ">
        <div class="container-fluid text-center">
            <a class="navbar-brand" href="{% url 'main_app:home' %}">LOGO</a>
        </div>
    </nav>
    <!-- navbar end -->
    <!-- main start -->
    <div class="card-group">
        <div class="card mb-3 text-center mt-5 full-page justify-content-center align-items-center">
            <img src="{{ object.image.url }}" class="card-img-top w-50 h-75" alt="{{ object.image.url }}">
            <div class="container">
                <div class="row justify-content-md-center">
                    <div class="col-12 col-sm-12 col-md-6 ">
                        <a class="btn btn-primary fs-3 mt-3" href="{{ object.image.url }}"
                            download="{{ object.image.url }}">Загрузить</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="card mb-3 text-center mt-5 full-page justify-content-center align-items-center">
            <img src="{{ object.modified_image.url }}" class="card-img-top w-50 h-75"
                alt="{{ object.modified_image.url }}">
            <div class="container">
                <div class="row justify-content-md-center">
                    <div class="col-12 col-sm-12 col-md-6 ">
                        <a class="btn btn-primary fs-3 mt-3" href="{{ object.all_files.url }}"
                            download="{{ object.all_files.url }}">Загрузить</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- main end -->
    <!-- footer start -->
    <footer class="footer text-center bg-primary p-4 bg-base-300 text-base-content">
        <div>
            <p>Copyright © 2024 - All right reserved by LOGO</p>
        </div>
    </footer>
    <!-- footer end -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>

</html>